spring.main.lazy-initialization=true
spring.main.banner-mode=off
spring.jmx.enabled=false

app.db.enabled=true
app.db.run-on-startup-fix=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.port=${SERVER_PORT:8080}
app.websocket.server-url=${APP_WEBSOCKET_SERVER_URL:ws://localhost:8080/ws-chat}

gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
gemini.api.key=${GEMINI_API_KEY:}
